### ISSUE TITLE
trainning on kitti

### ISSUE THREAD

**Issue by tryhere** [NVlabs/neuralrgbd#1]
Hi~
After reading the readme,I want to train your model on raw kitti dataset,but raw data have no ground truth.So could you tell me how to deal with them.

**Comment by cxlcl** [comment]
Hi, 
The raw data downloaded [here](http://www.cvlibs.net/datasets/kitti/raw_data.php) includes the 3D Velodyne point clouds, and you can use either the toolbox mentioned in that thread or [pyKitti](https://github.com/utiasSTARS/pykitti) to read the raw files ( getting the camera poses, GPUS measurements, Velodyne measurements etc.)
