### ISSUE TITLE
3d reconstruction

### ISSUE THREAD

**Issue by daodaofr** [NVlabs/neuralrgbd#17]
Nice work. 
Could you provide the code for 3d reconstruction to get the results in fig 8?

Thanks.

**Comment by cxlcl** [comment]
Thanks for the interest. 
Due to the IP issue I cannot share the code for that part. But it's very similar to  [voxel hashing ](https://github.com/niessner/VoxelHashing). Or you may use[ this](https://github.com/kysucix/fusibile)
