### ISSUE TITLE
live camera use past window src frames?

### ISSUE THREAD

**Issue by yvaine** [NVlabs/neuralrgbd#19]
Hi,
    I want to know if use live camera, the pose and frames all in past window, so when inference current frame use all past not forward? If inference past and future, it is delayed to inference current frame.

**Comment by cxlcl** [comment]
Hi @Yvaine ,

If I understand the question correctly, the implementation forms the local time window as (for t_win_r=2) [frame_t-2, frame_t-1, frame_t, frame_t+1, frame_t+2], where frame_t is the current frame (reference image) for which the depth estimation is performed. 
As a result, there is a two-frame delay in this case.

To avoid such delay, you can set frame_t+2 (the latest frame) as the reference image.

**Comment by yvaine** [comment]
Thank you. I understand.
