### ISSUE TITLE
Third case(from scanent) of figure 8 in the paper is from training dataset?

### ISSUE THREAD

**Issue by flamehaze1115** [NVlabs/neuralrgbd#2]
Hi, I have a question about the case of figure 8 in the paper.
The third case should be from scene0000_00, scene0000_01 and scene0000_02 of Scannet.
And the code/mdataloader/scanNet_split/scannet_train.txt should contains all the training data right? Although the txt file is random, I order it. 
I find that scene0000_00, scene0000_01 and scene0000_02 are quite in the training dataset.
In the paper, you compare DORN and DeMoN for this scene. So you use the three models to train on the same training dataset, and compare them on one training case, right?

**Comment by cxlcl** [comment]
We train our model on scanNet training set. The DORN and DeMoN are the ones directly downloaded (DORN trained on NYUv2, DeMoN trained on the datasets mentioned in their paper).
As a result, comparing the overall performance on the ScanNet is not fair for other methods, so we haven't include the numerical comparisons on scanNet. 

As for the third case in Fig.8:  
For that specific case, I picked the scene randomly (actually the very first sequence) from scanNet. Same observation as in Fig.8 still holds for other scanNet sequences that are not in the training set, as well as the sequences in the 7-scene dataset that are not included during training in any of the models.
