### ISSUE TITLE
Error in training on kitti dataset - valid batches check fail

### ISSUE THREAD

**Issue by Ahmadgafer** [NVlabs/neuralrgbd#4]
Hi,
I'm trying to run the training on the kitti dataset. I downloaded the raw data from the official website. The testing is working for me but when I launch the training script I get:
`Traceback (most recent call last):
  File "train_KVNet.py", line 384, in <module>
    main()
  File "train_KVNet.py", line 323, in main
    loss_v = LOSS[-1] 
IndexError: list index out of range
`
I tried to trace the problem and found that the condition in line 288 in train_KVnet.py always doesn't hold.
`
if n_valid_batch > 0:
`
I don't think I did something wrong as the testing is working on the same directory.
Any ideas on how to solve this issue?

**Comment by cxlcl** [comment]
This may indicate that the loader didn't find the raw images.
Could you set a breakpoint before `if n_valid_batch > 0:`, and look at the values for 
`local_info['ref_dats'][0]['scene_path']`
and
`local_info['ref_dats'][0]['img_path']` ? 

They should be something like '/datasets/kitti/rawdata/2011_09_26' and `'/datasets/kitti/rawdata/2011_09_26/2011_09_26_drive_0001_sync/image_02/data/0000000007.png'`

**Comment by Ahmadgafer** [comment]
@cxlcl  Thank you for your reply. I will check it.

**Comment by yearning-zenith** [comment]
> This may indicate that the loader didn't find the raw images.
> Could you set a breakpoint before `if n_valid_batch > 0:`, and look at the values for
> `local_info['ref_dats'][0]['scene_path']`
> and
> `local_info['ref_dats'][0]['img_path']` ?
> 
> They should be something like `/datasets/kitti/rawdata/2011_09_26` and `'/datasets/kitti/rawdata/2011_09_26/2011_09_26_drive_0001_sync/image_02/data/0000000007.png'`

I got path as you stated, but I check both batchsize as 1 on 1 gpu and batchsize as 2 and 4 on 2 gpu, all got local_info['is_valid'] as False.

**Comment by 777-en** [comment]
> This may indicate that the loader didn't find the raw images. Could you set a breakpoint before `if n_valid_batch > 0:`, and look at the values for `local_info['ref_dats'][0]['scene_path']` and `local_info['ref_dats'][0]['img_path']` ?
> 
> They should be something like `/datasets/kitti/rawdata/2011_09_26` and `'/datasets/kitti/rawdata/2011_09_26/2011_09_26_drive_0001_sync/image_02/data/0000000007.png'`

Hello, I met the same problem as @Ahmadgafer and I checked `local_info['ref_dats'][0]['scene_path']` and `local_info['ref_dats'][0]['img_path']`, which are all right. Is there any other possible reasons for this issue? please.
